executar_analises:
  description: >
    Execute as análises abaixo, com base nas instruções fornecidas e utilizando o seguinte CSV:

    {dataframe}

    Análises a executar:
    {analises}

    Para cada análise, gere:
    - titulos
    - Resumo da metodologia
    - Resultado encontrado
    - Interpretação
    - eixo_x: coluna categórica para o eixo X
    - eixo_y: coluna numérica para o eixo Y
    - tipo: "Linha", "Barra" ou "Pizza"

    A resposta deve ser um JSON com a seguinte estrutura:

    ```json
    [
      {
        "titulo": "...",
        "metodologia": "...",
        "resultado": "...",
        "interpretacao": "...",
        "eixo_x": "...",
        "eixo_y": "...",
        "tipo": "..."
      },
      ...
    ]
    ```
  expected_output: >
    Uma lista JSON com 5 os resultados das 5 análises explicados de forma clara.
  agent: executor_analitico
